#端口号
 server:
   port: 8002

 spring:
   application:
     name: springcloud-member
   cloud:
     config:
       profile: dev         #获取环境后缀（服务名称-环境名：springcloud-member-dev）
       discovery:
         service-id: config-server
         enabled: true
 eureka:
   client:
     serviceUrl:
       defaultZone: http://127.0.0.1:7001/eureka #,http://127.0.0.1:7002/eureka  #注册到eureka上面的地址
   instance:
     instance-id: springcloud-member-8002           #页面上显示的服务名称
     ip-address: true                               #鼠标放在服务名上坐下角显示ip

#刷新接口http://127.0.0.1:8888/ actuator/ bus-refresh
##开启消息总线
# management:
#   endpoints:
#     web:
#       exposure:
#         include: bus-refresh




