#端口号
 server:
   port: 8001

 spring:
   application:
     name: springcloud-member
 eureka:
   client:
     serviceUrl:
       defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka  #注册到eureka上面的地址
   instance:
     instance-id: springcloud-member-8001           #页面上显示的服务名称
     ip-address: true                               #鼠标放在服务名上坐下角显示ip




