#端口号
 server:
   port: 8010
#   tomcat:
#     max-threads: 10
#     max-connections: 10

 spring:
   application:
     name: springcloud-order
   cloud:
     config:
       profile: dev      #获取环境后缀（服务名称-环境名：springcloud-order-dev）
       discovery:
         service-id: config-server     #读取configserver注册地址
         enabled: true
 eureka:
   client:
     serviceUrl:
       defaultZone: http://127.0.0.1:7001/eureka #,http://127.0.0.1:7002/eureka  #注册到eureka上面的地址
   instance:
     instance-id: springcloud-order-8010           #页面上显示的服务名称
     ip-address: true                               #鼠标放在服务名上坐下角显示ip

###开启Hystrix断路器
 feign:
   hystrix:
     enabled: true
###引入actuator依赖
###配置开启监控断点
###对configclient获取远程服务器的配置信息进行[手动刷新]，类上须加@RefreshScope
###http://127.0.0.1:8010/actuator/refresh
 management:
   endpoints:
     web:
       exposure:
         include: "*"

#开启消息总线
# management:
#   endpoints:
#     web:
#       exposure:
#         include: bus-refresh




