###服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
###api网关端口号   http://127.0.0.1:80/member/orderToMember?userToken=211424
server:
  port: 8030
###网关名称
spring:
  application:
    name: service-zuul
  cloud:
    config:
    ####读取后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
        service-id: config-server
        enabled: true
###nginx+zull：访问地址：http://itlizx.nginx.com/member/orderToMember?userToken=211424
###开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"